FROM python:3.9.7-slim-buster

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

# install Nginx
RUN apt-get update && apt-get install -y nginx

# configure Nginx
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir /etc/nginx/ssl/
COPY certs/cert.pem /etc/nginx/ssl/
COPY certs/key.pem /etc/nginx/ssl/

# Expose port 80 for Nginx and port 5000 for Flask app
EXPOSE 80 5000

# Start Nginx and Flask app using supervisord
RUN apt-get update && apt-get install -y supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]

