version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      CONNETION_LINK: ${CONNECTION_LINK}
    volumes:
      - .:/app
    networks:
      - nginx_network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl/
    depends_on:
      - app
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge
