FROM python:3.9.7-slim-buster

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

# install Nginx
RUN apt-get update && apt-get install -y nginx

# configure Nginx
COPY nginx.conf /etc/nginx/nginx.conf



# Expose port 80 for Nginx and port 5000 for Flask app
EXPOSE 80 5000

# Start Nginx and Flask app using a startup script
COPY startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh
CMD ["/usr/local/bin/startup.sh"]
